title: MI TITULO SUPER POKEMON
theme: minima
author: YOP EL AUTOR SOY YOP
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  DESCRIPCION DE MI WEB HOLA SOY YO

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
